cp apply-config-sample.sh apply-config.sh
chmod 755 replace-config.sh
./replace-config.sh
cp default.pdf /var/www/bigbluebutton-default/
cp favicon.ico /var/www/bigbluebutton-default/
cp default.pptx /var/www/bigbluebutton-default/
cp index.html /var/www/bigbluebutton-default/
cp tr_TR.json /usr/share/meteor/bundle/programs/server/assets/app/locales/
cp logo.png /var/bigbluebutton/playback/presentation/2.0/
cp logo.png /var/bigbluebutton/playback/presentation/2.3/
cp ../seslerconf-enter_conf_pin.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/48000/
cp ../seslerconf-entry_sound.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/48000/
cp ../seslerconf-exit_sound.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/48000/
cp ../seslerconf-goodbye.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/48000/
cp ../seslerconf-has_joined.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/48000/
cp ../seslerconf-has_left.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/48000/
cp ../seslerconf-is-locked.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/48000/
cp ../seslerconf-is-unlocked.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/48000/
cp ../seslerconf-kicked.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/48000/
cp ../seslerconf-listener_in_conference.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/48000/
cp ../seslerconf-listeners_in_conference.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/48000/
cp ../seslerconf-locked.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/48000/
cp ../seslerconf-members_in_conference.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/48000/
cp ../seslerconf-muted.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/48000/
cp ../seslerconf-number_of_listeners.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/48000/
cp ../seslerconf-one_other_member_conference.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/48000/
cp ../seslerconf-one_other_person_conference.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/48000/
cp ../seslerconf-other_persons_conference.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/48000/
cp ../seslerconf-pin.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/48000/
cp ../seslerconf-qna_mode.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/48000/
cp ../seslerconf-unmuted.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/48000/
cp ../seslerconf-welcome.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/48000/
cp ../seslerconf-you_are_already_muted.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/48000/
cp ../seslerconf-you_are_now_bidirectionally_muted.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/48000/
cp ../seslerconf-alone.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/48000/
cp ../seslerconf-bad-pin.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/48000/
cp ../seslerconf-conference_is_full.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/48000/
cp ../seslerconf-conference_is_in_qna_mode.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/48000/
cp ../seslerconf-conference_will_start_shortly.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/48000/
cp ../seslerconf-enter_conf_number.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/48000/
cp ../seslerconf-enter_conf_pin.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/32000/
cp ../seslerconf-entry_sound.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/32000/
cp ../seslerconf-exit_sound.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/32000/
cp ../seslerconf-goodbye.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/32000/
cp ../seslerconf-has_joined.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/32000/
cp ../seslerconf-has_left.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/32000/
cp ../seslerconf-is-locked.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/32000/
cp ../seslerconf-is-unlocked.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/32000/
cp ../seslerconf-kicked.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/32000/
cp ../seslerconf-listener_in_conference.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/32000/
cp ../seslerconf-listeners_in_conference.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/32000/
cp ../seslerconf-locked.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/32000/
cp ../seslerconf-members_in_conference.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/32000/
cp ../seslerconf-muted.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/32000/
cp ../seslerconf-number_of_listeners.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/32000/
cp ../seslerconf-one_other_member_conference.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/32000/
cp ../seslerconf-one_other_person_conference.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/32000/
cp ../seslerconf-other_persons_conference.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/32000/
cp ../seslerconf-pin.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/32000/
cp ../seslerconf-qna_mode.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/32000/
cp ../seslerconf-unmuted.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/32000/
cp ../seslerconf-welcome.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/32000/
cp ../seslerconf-you_are_already_muted.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/32000/
cp ../seslerconf-you_are_now_bidirectionally_muted.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/32000/
cp ../seslerconf-alone.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/32000/
cp ../seslerconf-bad-pin.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/32000/
cp ../seslerconf-conference_is_full.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/32000/
cp ../seslerconf-conference_is_in_qna_mode.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/32000/
cp ../seslerconf-conference_will_start_shortly.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/32000/
cp ../seslerconf-enter_conf_number.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/32000/
cp ../seslerconf-enter_conf_pin.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/16000/
cp ../seslerconf-entry_sound.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/16000/
cp ../seslerconf-exit_sound.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/16000/
cp ../seslerconf-goodbye.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/16000/
cp ../seslerconf-has_joined.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/16000/
cp ../seslerconf-has_left.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/16000/
cp ../seslerconf-is-locked.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/16000/
cp ../seslerconf-is-unlocked.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/16000/
cp ../seslerconf-kicked.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/16000/
cp ../seslerconf-listener_in_conference.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/16000/
cp ../seslerconf-listeners_in_conference.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/16000/
cp ../seslerconf-locked.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/16000/
cp ../seslerconf-members_in_conference.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/16000/
cp ../seslerconf-muted.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/16000/
cp ../seslerconf-number_of_listeners.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/16000/
cp ../seslerconf-one_other_member_conference.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/16000/
cp ../seslerconf-one_other_person_conference.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/16000/
cp ../seslerconf-other_persons_conference.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/16000/
cp ../seslerconf-pin.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/16000/
cp ../seslerconf-qna_mode.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/16000/
cp ../seslerconf-unmuted.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/16000/
cp ../seslerconf-welcome.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/16000/
cp ../seslerconf-you_are_already_muted.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/16000/
cp ../seslerconf-you_are_now_bidirectionally_muted.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/16000/
cp ../seslerconf-alone.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/16000/
cp ../seslerconf-bad-pin.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/16000/
cp ../seslerconf-conference_is_full.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/16000/
cp ../seslerconf-conference_is_in_qna_mode.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/16000/
cp ../seslerconf-conference_will_start_shortly.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/16000/
cp ../seslerconf-enter_conf_number.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/16000/
cp ../seslerconf-enter_conf_pin.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/8000/
cp ../seslerconf-entry_sound.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/8000/
cp ../seslerconf-exit_sound.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/8000/
cp ../seslerconf-goodbye.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/8000/
cp ../seslerconf-has_joined.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/8000/
cp ../seslerconf-has_left.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/8000/
cp ../seslerconf-is-locked.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/8000/
cp ../seslerconf-is-unlocked.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/8000/
cp ../seslerconf-kicked.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/8000/
cp ../seslerconf-listener_in_conference.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/8000/
cp ../seslerconf-listeners_in_conference.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/8000/
cp ../seslerconf-locked.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/8000/
cp ../seslerconf-members_in_conference.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/8000/
cp ../seslerconf-muted.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/8000/
cp ../seslerconf-number_of_listeners.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/8000/
cp ../seslerconf-one_other_member_conference.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/8000/
cp ../seslerconf-one_other_person_conference.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/8000/
cp ../seslerconf-other_persons_conference.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/8000/
cp ../seslerconf-pin.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/8000/
cp ../seslerconf-qna_mode.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/8000/
cp ../seslerconf-unmuted.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/8000/
cp ../seslerconf-welcome.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/8000/
cp ../seslerconf-you_are_already_muted.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/8000/
cp ../seslerconf-you_are_now_bidirectionally_muted.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/8000/
cp ../seslerconf-alone.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/8000/
cp ../seslerconf-bad-pin.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/8000/
cp ../seslerconf-conference_is_full.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/8000/
cp ../seslerconf-conference_is_in_qna_mode.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/8000/
cp ../seslerconf-conference_will_start_shortly.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/8000/
cp ../seslerconf-enter_conf_number.wav /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/8000/
bbb-conf --restart
